### ISSUE TITLE
How to force portrait when taking a photo?

### ISSUE THREAD

**Issue by ManuelOrtega** [iException/BUKImagePickerController#4]
I want only portrait when presenting the camera controller. 

The problem is that when I present it initially in landscape, the view controller remains this way and when turning the device it's already flipped. However, there is no problem if the first time you present the camera in portrait mode.

I don't know if this is a bug or I'm not doing something correctly. But, I really need to present the camera controller in portrait.

Thank you in advance.

**Comment by yimingtang** [comment]
Hi @ManuelOrtega, I'm not sure if I realized you problem. I guess you want to present the camera only with portrait mode, but your app supports both portrait and landscape mode. Am I right?

The camera will automatically rotate itself if you claim you app supports both portrait and landscape. Otherwise, it won't. A quick solution is to turn off the `interfaceRotatesWithOrientation` option of `fastCamera` in `BUKCameraViewController`.

For example:

``` objc
BUKCameraViewController *cameraViewController = ...
cameraViewController.fastCamera.interfaceRotatesWithOrientation = NO;
// Set other options
// Present your camera
```

**Comment by ManuelOrtega** [comment]
Ok, that was it. My app does not support landscape orientations, so forcing may there is no rotation solved my problem. However, I added this line in the BUKCameraViewController fastcamera init method, since in the other place, this property was not recognised.

Thank you very much!

P.S. I have another issue that you may be able to solve, but I'll open another one, you may close this one.
